import type { Metadata } from "next"

import "./globals.scss"
import "../public/fonts/fonts.css"
import { SmoothScrollProvider } from "@/components/common"
import { Header } from "@/components/layout"

export const metadata: Metadata = {
    title: "Inchapin",
    description: "Generated by create next app",
    viewport: {
        width: "device-width",
        initialScale: 1,
        maximumScale: 1,
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <Header />

                <SmoothScrollProvider>{children}</SmoothScrollProvider>
            </body>
        </html>
    )
}
