export { Player } from "./player/Player"
export { Modal } from "./modal/Modal"
export { Form } from "./form/Form"
export { BurgerMenu } from "./burgerMenu/BurgerMenu"
export { VideoTheater } from "./videoTheater/VideoTheater"
